on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

jobs:
  pre-release:
    uses: abbgrade/PsBuildTasks/.github/workflows/pre-release-windows.yml@1.14.5
    with:
      module-name: PsBuildTasks
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
