on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@1.14.2
    with:
      module-name: PsBuildTasks
      force-publish: false
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
