on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    uses: abbgrade/PsBuildTasks/.github/workflows/release-windows.yml@fd9646ab810c231ce4709538886a71eb2c0b35aa
    with:
      module-name: PsBuildTasks
    secrets:
      ps-gallery-key: ${{ secrets.PS_GALLERY_KEY }}
